{% set name = "showspectra" %}
{% set data = load_setup_py_data() %}


package:
  name: "{{ name|lower }}"
  version: "{{ data.get('version') }}"

source:
  git_tag: master
  git_url: https://github.com/darioflute/showspectra.git

build:
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.7
    - numpy >=1.9.3
    - matplotlib >=2.1.1
        
test:
  imports:
    - showspectra

about:
  home: https://github.com/darioflute/showspectra
  license: GPL3
  license_file: LICENSE
  description: 'Package to analyze multi-object spectra'
